<?php

// ----------------------------------------------------------------------------------------------------
// - Display Errors
// ----------------------------------------------------------------------------------------------------
ini_set('display_errors', 'On');
ini_set('html_errors', 0);

// ----------------------------------------------------------------------------------------------------
// - Error Reporting
// ----------------------------------------------------------------------------------------------------
error_reporting(-1);

// ----------------------------------------------------------------------------------------------------
// - Shutdown Handler
// ----------------------------------------------------------------------------------------------------
function ShutdownHandler()
{
    if(@is_array($error = @error_get_last()))
    {
        return(@call_user_func_array('ErrorHandler', $error));
    };

    return(TRUE);
};

register_shutdown_function('ShutdownHandler');

// ----------------------------------------------------------------------------------------------------
// - Error Handler
// ----------------------------------------------------------------------------------------------------
function ErrorHandler($type, $message, $file, $line)
{
    $_ERRORS = Array(
        0x0001 => 'E_ERROR',
        0x0002 => 'E_WARNING',
        0x0004 => 'E_PARSE',
        0x0008 => 'E_NOTICE',
        0x0010 => 'E_CORE_ERROR',
        0x0020 => 'E_CORE_WARNING',
        0x0040 => 'E_COMPILE_ERROR',
        0x0080 => 'E_COMPILE_WARNING',
        0x0100 => 'E_USER_ERROR',
        0x0200 => 'E_USER_WARNING',
        0x0400 => 'E_USER_NOTICE',
        0x0800 => 'E_STRICT',
        0x1000 => 'E_RECOVERABLE_ERROR',
        0x2000 => 'E_DEPRECATED',
        0x4000 => 'E_USER_DEPRECATED'
    );

    if(!@is_string($name = @array_search($type, @array_flip($_ERRORS))))
    {
        $name = 'E_UNKNOWN';
    };

    return(print(@sprintf("%s Error in file \xBB%s\xAB at line %d: %s\n", $name, @basename($file), $line, $message)));
};

$old_error_handler = set_error_handler("ErrorHandler");

//***********actual php client code starts here....*************
//var_dump(123); testcode for manual debugging

// Include DatabaseHelper.php file
require_once('DatabaseHelper.php');

// Instantiate DatabaseHelper class
$database = new DatabaseHelper();

// Get parameter 'kundenID', 'vorname', 'nachname' etc. from GET Request
// Btw. you can see the parameters in the URL if they are set
$kundenID = '';
if (isset($_GET['kundenID'])) {
    $kundenID = $_GET['kundenID'];
}

$nachname = '';
if (isset($_GET['nachname'])) {
    $nachname = $_GET['nachname'];
}

$vorname = '';
if (isset($_GET['vorname'])) {
    $vorname = $_GET['vorname'];
}

$ort = '';
if (isset($_GET['ort'])) {
    $ort = $_GET['ort'];
}

$plz = '';
if (isset($_GET['plz'])) {
    $plz = $_GET['plz'];
}

$strasse = '';
if (isset($_GET['strasse'])) {
    $strasse = $_GET['strasse'];
}

$hausNr = '';
if (isset($_GET['hausNr'])) {
    $hausNr = $_GET['hausNr'];
}

//Fetch data from database
$kunden_array = $database->selectFromKundeWhere($kundenID, $vorname, $nachname);
?>

<html>
<head>
    <title>DBS Projekt-Webshop</title>
<style>
	body {background-color: grey;}
	h1 {
		font-weight: bold;
		text-decoration: underline;
	}
</style>
</head>

<body>
<br>
<h1>PHP Client for Webshop</h1>
<a href="artikel.php">
    artikel
</a>
<!-- Add Kunde -->
<h2>Kunde hinzufuegen: </h2>
<form method="post" action="addKunde.php">
    <!-- Kunden ID is not needed, because its autogenerated by the database -->

    <!-- NName textbox -->
    <div>
        <label for="new_nachname">Nachname:</label>
        <input id="new_nachname" name="nachname" type="text" maxlength="20">
    </div>
    <br>

    <!-- VName textbox -->
    <div>
        <label for="new_vorname">Vorname:</label>
        <input id="new_vorname" name="vorname" type="text" maxlength="20">
    </div>
    <br>
	
	    <!-- ort textbox -->
    <div>
        <label for="new_ort">Ort:</label>
        <input id="new_ort" name="ort" type="text" maxlength="20">
    </div>
    <br>
	
	    <!-- plz textbox -->
    <div>
        <label for="new_plz">PLZ:</label>
        <input id="new_plz" name="plz" type="text" maxlength="20">
    </div>
    <br>
	
		    <!-- strasse textbox -->
    <div>
        <label for="new_strasse">Strasse:</label>
        <input id="new_strasse" name="strasse" type="text" maxlength="40">
    </div>
    <br>
	
		    <!-- hausNr textbox -->
    <div>
        <label for="new_hausNr">Haus Nr:</label>
        <input id="new_hausNr" name="hausNr" type="text" maxlength="20">
    </div>
    <br>

    <!-- submit button -->
    <div>
        <button type="submit">
            Kunde hinzufuegen
        </button>
    </div>
</form>
<br>
<hr>

<!-- Delete Kunde -->
<h2>Entfernen Kunde: </h2>
<form method="post" action="delKunde.php">
    <!-- ID textbox -->
    <div>
        <label for="del_nachname">ID:</label>
        <input id="del_nachname" name="kundenID" type="number" min="0">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button type="submit">
            Kunde entfernen
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search form -->
<h2>Kunden Suche:</h2>
<form method="get">
    <!-- ID textbox:-->
    <div>
        <label for="kundenID">ID:</label>
        <input id="kundenID" name="kundenID" type="number" value='<?php echo $kundenID; ?>' min="0">
    </div>
    <br>

    <!-- Name textbox:-->
    <div>
        <label for="nachname">Vorname:</label>
        <input id="nachname" name="nachname" type="text" class="form-control input-md" value='<?php echo $nachname; ?>'
               maxlength="20">
    </div>
    <br>

    <!-- surname textbox:-->
    <div>
        <label for="vorname">Nachname:</label>
        <input id="vorname" name="vorname" type="text"
               value='<?php echo $vorname; ?>' maxlength="20">
    </div>
    <br>

    <!-- Submit button -->
    <div>
        <button id='submit' type='submit'>
            Suche
        </button>
    </div>
</form>
<br>
<hr>

<!-- Search result -->
<h2>Person Search Result:</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Nachname</th>
        <th>Vorname</th>
		<th>Ort</th>
		<th>PLZ</th>
		<th>Strasse</th>
		<th>HausNr</th>
    </tr>
    <?php foreach ($kunden_array as $kunde) : ?>
        <tr>
            <td><?php echo $kunde['KUNDENID']; ?>  </td>
            <td><?php echo $kunde['NACHNAME']; ?>  </td>
            <td><?php echo $kunde['VORNAME']; ?>  </td>
			<td><?php echo $kunde['ORT']; ?>  </td>
            <td><?php echo $kunde['PLZ']; ?>  </td>
            <td><?php echo $kunde['STRASSE']; ?>  </td>
			<td><?php echo $kunde['HAUSNR']; ?>  </td>
        </tr>
    <?php endforeach; ?>
</table>

</body>
</html>